question_data = [{"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "All program codes have to be compiled into an executable file in order to be run. This "
                              "file can then be executed on any machine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "&quot;Windows NT&quot; is a monolithic kernel.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The open source program Redis is a relational database server.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= "
                              "1&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "MacOS is based on Linux.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen "
                              "resolution.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Science: Computers",
                  "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of "
                              "memory.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "AMD created the first consumer 64-bit processor.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "The Windows ME operating system was released in the year 2000.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
